package bookstoreUiAddMembre;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import bookstore.entites.Client;
import bookstore.service.ServiceOuvrage;
import javafx.event.ActionEvent;

public class membre_addController {
	@FXML
	private TextField name;
	@FXML
	private TextField id;
	@FXML
	private TextField tel;
	@FXML
	private TextField email;
	@FXML
	private TextField pwd;
	@FXML
	private Button save;
	@FXML
	private Button cancel;

	// Event Listener on Button[#save].onAction
	@FXML
	public void addMember(ActionEvent event) {
		// TODO Autogenerated
		ServiceOuvrage so = new ServiceOuvrage();
		Client cl=new Client();
		String mName=name.getText();
		String mid=id.getText();
		String mtelephone=tel.getText();
		String memail=email.getText();
		Boolean mflag=mName.isEmpty()||mid.isEmpty()||mtelephone.isEmpty()||memail.isEmpty();
		cl.setId(id.getText());
		cl.setName(name.getText());
		cl.setEmail(email.getText());
		cl.setTel(tel.getText());
		cl.setPwd(pwd.getText());
		
		if(mflag) {
			Alert alert = new Alert(Alert.AlertType.ERROR);
			alert.setHeaderText(null);
			alert.setContentText("Entrer tous les champs");
			alert.showAndWait();
			return;
		}
		so.ajouterClient(cl);
		Stage stage=(Stage) save.getScene().getWindow();
		stage.close();
	}
	// Event Listener on Button[#cancel].onAction
	@FXML
	public void cancel(ActionEvent event) {
		// TODO Autogenerated
		Stage stage=(Stage) cancel.getScene().getWindow();
		stage.close();
	}
}
