package listEmprunts;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ResourceBundle;

import bookstore.service.ServiceOuvrage;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableColumn;

public class list_empruntClientController  implements Initializable{
	@FXML
	private AnchorPane rootPane;
	@FXML
	private TableView tableView;
	@FXML
	private TableColumn bookCol;
	@FXML
	private TableColumn clientCol;
	@FXML
	private TableColumn dateCol;
	@FXML
	private TableColumn renewCol;

	// Event Listener on MenuItem.onAction
	@FXML
	public void handleOuvDeleteOption(ActionEvent event) {
		// TODO Autogenerated
		initCol();
		loadData();
	}
	private void initCol() {
		bookCol.setCellValueFactory(new PropertyValueFactory<>("bookName"));
		clientCol.setCellValueFactory(new PropertyValueFactory<>("memberName"));
		dateCol.setCellValueFactory(new PropertyValueFactory<>("issueTime"));
		renewCol.setCellValueFactory(new PropertyValueFactory<>("renew_count"));
	}

	private void loadData() {
		ServiceOuvrage so = new ServiceOuvrage();
		//tableView.getItems().setAll(so.afficherMesEmprunt(c));
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
	}
}
